server:
  port: 8080
spring:
  thymeleaf:
    suffix: .html
    #mode: LEGACYHTML5
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  devtools:
    restart:
      # 是否启用热部署
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      # devtools开发工具热加载（重启）排除静态文件
      additional-exclude: resources/**
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  messages:
    basename: i18n/messages
#  http:
#    multipart:
#      max-file-size: 500Mb
#      max-request-size: 5000Mb
#mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhangbaohpu.springboot.common.entity
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", ASSIGN_UUID:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

